export interface FAQItem {
  question: string;
  answer: string;
}

export const faqData: FAQItem[] = [
  {
    question: 'How long does it take to launch an MVP with Buzooka?',
    answer:
      'With Buzooka, you can launch a production-ready MVP in days instead of weeks or months. Our AI-powered platform automates architecture, codebase generation, cloud infrastructure setup, and CI/CD pipeline configuration. Buzooka does not generate code specific to your product. The exact timeline depends on your project complexity, but most users have their MVP running within 2-5 days.',
  },
  {
    question: 'What tech stacks and frameworks does Buzooka support?',
    answer:
      'Buzooka supports a wide range of modern technologies including React, Svelte, Vue, Next.js for frontend development; Node.js, Python, and TypeScript for backend services; and Flutter for mobile app development. We also integrate with popular cloud providers like AWS, GCP, Azure, DigitalOcean, and Netlify. Our platform generates AI-friendly, well-architected code that follows industry best practices.',
  },
  {
    question: 'Do I own the code generated by Buzooka?',
    answer:
      'Yes, absolutely! You have complete ownership of all code generated by Buzooka. The codebase is delivered to your GitHub repository, and you maintain full control over it. There are no licensing restrictions or vendor lock-in. You can modify, extend, or even migrate away from Buzooka at any time. We believe in empowering founders with true ownership of their product.',
  },
  {
    question: 'Can I use my own cloud provider account?',
    answer:
      'Yes! Buzooka follows a "Bring Your Own Cloud" (BYOC) approach. You can connect your existing DigitalOcean account (AWS, GCP, Azure - Coming Soon), and we\'ll provision the infrastructure directly in your account. This means you maintain full control over your cloud resources, billing, and data. You\'re never locked into our infrastructure, and you can see exactly what resources are being used.',
  },
  {
    question: 'What\'s included in the Scout plan?',
    answer:
      'The Scout plan includes unlimited projects, unlimited nodes, AI-powered architecture planning, repository generation with AI-friendly code, cloud provisioning automation, node deployments, and a free one-time consultation call. At $9/month (80% off the regular $49 price during prelaunch), it\'s perfect for solo developers, side projects, and early-stage MVPs. You get access to all core features needed to build and launch production-ready applications.',
  },
  {
    question: 'How does Buzooka handle CI/CD and deployments?',
    answer:
      'Buzooka automatically sets up a complete CI/CD pipeline for your project. When you push code to your repository, and on-demand, it builds your application, and deploys it to your chosen cloud environment. We configure Docker containers, set up environment variables, manage database migrations, and handle zero-downtime deployments. You get a production-grade deployment workflow from day one.',
  },
  {
    question: 'Is Buzooka suitable for non-technical founders?',
    answer:
      'Yes! Buzooka is designed to be accessible for non-technical founders who want to launch their product without needing a technical co-founder or expensive development team. Our AI architect helps you design your system architecture through simple prompts, and our platform handles all the complex DevOps work. We also offer free consultation calls and on-demand competitively priced developer support to guide you through the process.',
  },
  {
    question: 'What makes Buzooka\'s code "AI-friendly"?',
    answer:
      'AI-friendly code means the generated codebase is structured, documented, and organized in a way that AI coding assistants (like GitHub Copilot, Cursor, or Claude) can easily understand and work with. We use clear naming conventions, comprehensive comments, modular architecture, and consistent patterns. This makes it easier for you to extend your application using AI tools, significantly accelerating your development workflow.',
  },
  {
    question: 'Can I scale my application built with Buzooka?',
    answer:
      'Absolutely! Buzooka generates production-grade architecture designed for scalability from the start. We implement proper separation of concerns, microservices architecture where appropriate, containerization with Docker, and cloud-native patterns. As your user base grows, you can easily scale horizontally by adding more instances, implement load balancing, and optimize database performance.',
  },
  {
    question: 'What kind of support does Buzooka provide?',
    answer:
      'All Scout plan users get a free one-time consultation call to help you get started. We also offer on-demand architect and developer services for additional support. Our documentation covers common use cases, and we\'re building a community of founders and developers. For enterprise customers, we provide dedicated account managers and priority support. You can also book consultation calls to discuss your specific architecture needs or get help with feature development.',
  },
];
