import {
  Chrome,
  Database,
  Lock,
  Server,
  Smartphone,
  Search,
  Video,
  ShoppingCart,
  Twitter,
  Cpu,
  Globe,
  HardDrive,
  MessageSquare,
  Zap,
  Map,
  User,
  Bell,
  Clock,
  Calendar,
} from 'lucide-svelte';

export const presets = {
  consultation: {
    nodes: [
      {
        id: '1',
        type: 'web',
        label: 'Your Request',
        x: 0,
        y: 100,
        icon: User,
      },
      {
        id: '2',
        type: 'service',
        label: 'Scheduler',
        x: 250,
        y: 100,
        icon: Clock,
      },
      {
        id: '3',
        type: 'service',
        label: 'Calendar',
        x: 500,
        y: 50,
        icon: Calendar,
      },
      {
        id: '4',
        type: 'service',
        label: 'Notification',
        x: 500,
        y: 150,
        icon: Bell,
      },
    ],
    edges: [
      { source: '1', target: '2' },
      { source: '2', target: '3' },
      { source: '2', target: '4' },
    ],
  },
  google: {
    nodes: [
      {
        id: '1',
        type: 'service',
        label: 'Crawler',
        x: 0,
        y: 50,
        icon: Globe,
      },
      {
        id: '2',
        type: 'service',
        label: 'Indexer',
        x: 250,
        y: 50,
        icon: Database,
      },
      {
        id: '3',
        type: 'database',
        label: 'Search Index',
        x: 500,
        y: 50,
        icon: HardDrive,
      },
      {
        id: '4',
        type: 'web',
        label: 'Frontend',
        x: 250,
        y: 200,
        icon: Search,
      },
    ],
    edges: [
      { source: '1', target: '2' },
      { source: '2', target: '3' },
      { source: '4', target: '3' },
    ],
  },
  netflix: {
    nodes: [
      {
        id: '1',
        type: 'mobile',
        label: 'Client App',
        x: 0,
        y: 100,
        icon: Smartphone,
      },
      {
        id: '2',
        type: 'service',
        label: 'API Gateway',
        x: 250,
        y: 100,
        icon: Server,
      },
      {
        id: '3',
        type: 'service',
        label: 'Transcoder',
        x: 500,
        y: 0,
        icon: Video,
      },
      {
        id: '4',
        type: 'database',
        label: 'Content DB',
        x: 500,
        y: 200,
        icon: Database,
      },
    ],
    edges: [
      { source: '1', target: '2' },
      { source: '2', target: '3' },
      { source: '2', target: '4' },
    ],
  },
  uber: {
    nodes: [
      {
        id: '1',
        type: 'mobile',
        label: 'Rider App',
        x: 0,
        y: 50,
        icon: Smartphone,
      },
      {
        id: '2',
        type: 'mobile',
        label: 'Driver App',
        x: 0,
        y: 150,
        icon: Smartphone,
      },
      {
        id: '3',
        type: 'service',
        label: 'Dispatch',
        x: 250,
        y: 100,
        icon: Zap,
      },
      {
        id: '4',
        type: 'service',
        label: 'Maps Service',
        x: 500,
        y: 100,
        icon: Map,
      },
    ],
    edges: [
      { source: '1', target: '3' },
      { source: '2', target: '3' },
      { source: '3', target: '4' },
    ],
  },
  amazon: {
    nodes: [
      {
        id: '1',
        type: 'web',
        label: 'Storefront',
        x: 0,
        y: 100,
        icon: ShoppingCart,
      },
      {
        id: '2',
        type: 'service',
        label: 'Order Svc',
        x: 250,
        y: 50,
        icon: Server,
      },
      {
        id: '3',
        type: 'service',
        label: 'Inventory',
        x: 250,
        y: 150,
        icon: Database,
      },
      {
        id: '4',
        type: 'database',
        label: 'Main DB',
        x: 500,
        y: 100,
        icon: HardDrive,
      },
    ],
    edges: [
      { source: '1', target: '2' },
      { source: '1', target: '3' },
      { source: '2', target: '4' },
      { source: '3', target: '4' },
    ],
  },
  openai: {
    nodes: [
      {
        id: '1',
        type: 'service',
        label: 'Training',
        x: 0,
        y: 100,
        icon: Cpu,
      },
      {
        id: '2',
        type: 'database',
        label: 'Weights',
        x: 250,
        y: 100,
        icon: Database,
      },
      {
        id: '3',
        type: 'service',
        label: 'Inference API',
        x: 500,
        y: 100,
        icon: Zap,
      },
      {
        id: '4',
        type: 'web',
        label: 'ChatGPT',
        x: 750,
        y: 100,
        icon: MessageSquare,
      },
    ],
    edges: [
      { source: '1', target: '2' },
      { source: '2', target: '3' },
      { source: '4', target: '3' },
    ],
  },
  x: {
    nodes: [
      {
        id: '1',
        type: 'mobile',
        label: 'Mobile App',
        x: 0,
        y: 100,
        icon: Smartphone,
      },
      {
        id: '2',
        type: 'service',
        label: 'Timeline',
        x: 250,
        y: 50,
        icon: Twitter,
      },
      {
        id: '3',
        type: 'service',
        label: 'Tweet Svc',
        x: 250,
        y: 150,
        icon: MessageSquare,
      },
      {
        id: '4',
        type: 'database',
        label: 'Graph DB',
        x: 500,
        y: 100,
        icon: Database,
      },
    ],
    edges: [
      { source: '1', target: '2' },
      { source: '1', target: '3' },
      { source: '2', target: '4' },
      { source: '3', target: '4' },
    ],
  },
};
